full_name = "Ubuntu 22.04"
short_name = "ubuntu2204"

[stigs]
[stigs.v1r1]
release_date = 2024-04-04
[stigs.v2r1]
release_date = 2024-07-17
[stigs.v2r2]
release_date = 2024-10-23
[stigs.v2r3]
release_date = 2025-01-28
[stigs.v2r4]
release_date = 2025-04-07
