full_name = "Microsoft Windows 11"
short_name = "win11"

[stigs]
[stigs.v1r5]
release_date = 2023-11-02
[stigs.v1r6]
release_date = 2024-05-02
[stigs.v2r1]
release_date = 2024-07-17
[stigs.v2r2]
release_date = 2024-10-16
[stigs.v2r3]
release_date = 2025-04-07
