full_name = "macOS 14 - Sonoma"
short_name = "macos14"

[stigs]
[stigs.v1r1]
release_date = 2024-01-19
[stigs.v1r2]
release_date = 2024-04-23
[stigs.v2r1]
release_date = 2024-07-17
[stigs.v2r2]
release_date = 2024-10-23
[stigs.v2r3]
release_date = 2025-01-28
