full_name = "Ubuntu 18.04"
short_name = "ubuntu1804"

[stigs]
[stigs.v2r10]
release_date = 2023-01-23
[stigs.v2r11]
release_date = 2023-04-24
[stigs.v2r12]
release_date = 2023-10-23
[stigs.v2r13]
release_date = 2024-01-23
[stigs.v2r14]
release_date = 2024-04-23
[stigs.v2r15]
release_date = 2024-07-17
