full_name = "Microsoft Windows Server 2016"
short_name = "winserv2016"

[stigs]
[stigs.v2r7]
release_date = 2023-10-30
[stigs.v2r8]
release_date = 2024-05-02
[stigs.v2r9]
release_date = 2024-10-16
[stigs.v2r10]
release_date = 2025-01-28
