full_name = "Red Hat Ansible Automation Controller Web Server"
short_name = "appc_ws"
[stigs]
[stigs.v1r1]
release_date = 2023-04-10
[stigs.v1r2]
release_date = 2023-10-23
[stigs.v2r1]
release_date = 2024-07-17
