full_name = "Security Requirements Guide - Mainframe Product"
short_name = "srg-mainframe"

[stigs]
[stigs.v3r1]
release_date = 2024-07-17
[stigs.v3r2]
release_date = 2024-10-23
[stigs.v3r3]
release_date = 2025-01-28
